## Functions for creating a matrix that caches
## its inverse.

## Make an object from a matrix that can
## cache its inverse.
##
## param `x`: a matrix; default: `matrix()`
##
## returns: a list with functions
## `get()`: get the value of the matrix
## `set()`: set the value of the stored matrix
## `setInverse()`: set the value of the inverse of the matrix
## `getInverse()`: return the value of the inverse of
##                 the matrix, or NULL if not yet set
makeCacheMatrix <- function(x = matrix()) {
    inverse <- NULL
    set <- function (y) {
        x <<- y
        inverse <<- NULL
    }
    get <- function () x
    setInverse <- function (inv) inverse <<- inv
    getInverse <- function () inverse
    list(set = set, get = get,
         setInverse = setInverse,
         getInverse = getInverse)
}


## Get the inverse of matrix `x`. Return inverse
## from cache if available, otherwise, compute and
## return the inverse, storing it in cache.
## Messages when returning from cache.
##
## param `x`: a matrix object generated by
##            `makeCacheMatrix()`
## return: the inverse of `x`
cacheSolve <- function(x, ...) {
    ## Return a matrix that is the inverse of 'x'
    inv <- x$getInverse()
    if (!is.null(inv)) {
        message('returning inverse from cache')
        return(inv)
    }
    data <- x$get()
    inv <- solve(data, ...)
    x$setInverse(inv)
    inv
}
